import {
    bounceOnEnterAnimation,
    flashOnEnterAnimation,
    pulseOnEnterAnimation,
    rubberBandOnEnterAnimation,
    shakeOnEnterAnimation,
    swingOnEnterAnimation,
    tadaOnEnterAnimation,
    wobbleOnEnterAnimation,
    jelloOnEnterAnimation,
    flipOnEnterAnimation,
    bounceInOnEnterAnimation,
    bounceOutOnLeaveAnimation,
    bounceInUpOnEnterAnimation,
    bounceOutDownOnLeaveAnimation,
    bounceInDownOnEnterAnimation,
    bounceOutUpOnLeaveAnimation,
    bounceInLeftOnEnterAnimation,
    bounceInRightOnEnterAnimation,
    bounceOutLeftOnLeaveAnimation,
    bounceOutRightOnLeaveAnimation,
    fadeInOnEnterAnimation,
    fadeInUpOnEnterAnimation,
    fadeInDownOnEnterAnimation,
    fadeInLeftOnEnterAnimation,
    fadeInRightOnEnterAnimation,
    fadeInUpBigOnEnterAnimation,
    fadeInDownBigOnEnterAnimation,
    fadeInLeftBigOnEnterAnimation,
    fadeInRightBigOnEnterAnimation,
    fadeOutOnLeaveAnimation,
    fadeOutUpOnLeaveAnimation,
    fadeOutDownOnLeaveAnimation,
    fadeOutLeftOnLeaveAnimation,
    fadeOutRightOnLeaveAnimation,
    fadeOutUpBigOnLeaveAnimation,
    fadeOutDownBigOnLeaveAnimation,
    fadeOutLeftBigOnLeaveAnimation,
    fadeOutRightBigOnLeaveAnimation,
    flipInXOnEnterAnimation,
    flipInYOnEnterAnimation,
    flipOutXOnLeaveAnimation,
    flipOutYOnLeaveAnimation,
    lightSpeedInOnEnterAnimation,
    lightSpeedOutOnLeaveAnimation,
    rotateInOnEnterAnimation,
    rotateInUpLeftOnEnterAnimation,
    rotateInUpRightOnEnterAnimation,
    rotateInDownLeftOnEnterAnimation,
    rotateInDownRightOnEnterAnimation,
    rotateOutOnLeaveAnimation,
    rotateOutUpLeftOnLeaveAnimation,
    rotateOutUpRightOnLeaveAnimation,
    rotateOutDownLeftOnLeaveAnimation,
    rotateOutDownRightOnLeaveAnimation,
    slideInRightOnEnterAnimation,
    slideInUpOnEnterAnimation,
    slideInDownOnEnterAnimation,
    slideInLeftOnEnterAnimation,
    slideOutUpOnLeaveAnimation,
    slideOutDownOnLeaveAnimation,
    slideOutLeftOnLeaveAnimation,
    slideOutRightOnLeaveAnimation,
    zoomInOnEnterAnimation,
    zoomInUpOnEnterAnimation,
    zoomInDownOnEnterAnimation,
    zoomInLeftOnEnterAnimation,
    zoomInRightOnEnterAnimation,
    zoomOutOnLeaveAnimation,
    zoomOutUpOnLeaveAnimation,
    zoomOutDownOnLeaveAnimation,
    zoomOutLeftOnLeaveAnimation,
    zoomOutRightOnLeaveAnimation,
    hingeOnLeaveAnimation,
    jackInTheBoxOnEnterAnimation,
    rollInOnEnterAnimation,
    rollOutOnLeaveAnimation,
    expandOnEnterAnimation,
    collapseOnLeaveAnimation,
    fadeInExpandOnEnterAnimation,
    fadeOutCollapseOnLeaveAnimation
} from 'angular-animations';

import {
    animation, trigger, animateChild, group,
    transition, animate, style, query
} from '@angular/animations';


export const Zooming = [
    zoomInOnEnterAnimation(),
    zoomInUpOnEnterAnimation(),
    zoomInDownOnEnterAnimation(),
    zoomInLeftOnEnterAnimation(),
    zoomInRightOnEnterAnimation(),
    zoomOutOnLeaveAnimation(),
    zoomOutUpOnLeaveAnimation(),
    zoomOutDownOnLeaveAnimation(),
    zoomOutLeftOnLeaveAnimation(),
    zoomOutRightOnLeaveAnimation(),
];
export const Sliding = [
    slideInRightOnEnterAnimation(),
    slideInUpOnEnterAnimation(),
    slideInDownOnEnterAnimation(),
    slideInLeftOnEnterAnimation(),
    slideOutUpOnLeaveAnimation(),
    slideOutDownOnLeaveAnimation(),
    slideOutLeftOnLeaveAnimation(),
    slideOutRightOnLeaveAnimation(),
];
export const Bouncing = [
    bounceInRightOnEnterAnimation({ anchor: 'enter1' }),
    bounceInRightOnEnterAnimation({ anchor: 'enter2', delay: 100 }),
    bounceInRightOnEnterAnimation({ anchor: 'enter3', delay: 200, animateChildren: 'none' }),
    bounceOnEnterAnimation(),
    bounceInOnEnterAnimation(),
    bounceInUpOnEnterAnimation(),
    bounceOutOnLeaveAnimation(),
    bounceOutDownOnLeaveAnimation(),
    bounceInDownOnEnterAnimation(),
    bounceOutUpOnLeaveAnimation(),
    bounceInLeftOnEnterAnimation({ anchor: 'enter4', delay: 200, animateChildren: 'none' }),
    bounceInRightOnEnterAnimation(),
    bounceOutLeftOnLeaveAnimation(),
    bounceOutRightOnLeaveAnimation()
];
export const Fading = [
    fadeInOnEnterAnimation(),
    fadeInUpOnEnterAnimation(),
    fadeInDownOnEnterAnimation(),
    fadeInLeftOnEnterAnimation(),
    fadeInRightOnEnterAnimation(),
    fadeInUpBigOnEnterAnimation(),
    fadeInDownBigOnEnterAnimation(),
    fadeInLeftBigOnEnterAnimation(),
    fadeInRightBigOnEnterAnimation(),
    fadeOutOnLeaveAnimation(),
    fadeOutUpOnLeaveAnimation(),
    fadeOutDownOnLeaveAnimation(),
    fadeOutLeftOnLeaveAnimation(),
    fadeOutRightOnLeaveAnimation(),
    fadeOutUpBigOnLeaveAnimation(),
    fadeOutDownBigOnLeaveAnimation(),
    fadeOutLeftBigOnLeaveAnimation(),
    fadeOutRightBigOnLeaveAnimation(),
];
export const Flippers = [
    flipOnEnterAnimation(),
    flipInXOnEnterAnimation(),
    flipInYOnEnterAnimation(),
    flipOutXOnLeaveAnimation(),
    flipOutYOnLeaveAnimation(),
];
export const LightSpeed = [
    lightSpeedInOnEnterAnimation(),
    lightSpeedOutOnLeaveAnimation(),
];
export const Rotating = [
    rotateInOnEnterAnimation(),
    rotateInUpLeftOnEnterAnimation(),
    rotateInUpRightOnEnterAnimation(),
    rotateInDownLeftOnEnterAnimation(),
    rotateInDownRightOnEnterAnimation(),
    rotateOutOnLeaveAnimation(),
    rotateOutUpLeftOnLeaveAnimation(),
    rotateOutUpRightOnLeaveAnimation(),
    rotateOutDownLeftOnLeaveAnimation(),
    rotateOutDownRightOnLeaveAnimation(),
];
export const Specials = [
    jackInTheBoxOnEnterAnimation(),
    rollInOnEnterAnimation(),
    rollOutOnLeaveAnimation(),
    hingeOnLeaveAnimation(),
];
export const Expand = [
    expandOnEnterAnimation({ duration: 400 }),
    collapseOnLeaveAnimation({ duration: 400 }),
    fadeInExpandOnEnterAnimation({ duration: 400 }),
    fadeOutCollapseOnLeaveAnimation({ duration: 400 })
];
export const Others = [
    flashOnEnterAnimation(),
    pulseOnEnterAnimation(),
    rubberBandOnEnterAnimation(),
    shakeOnEnterAnimation(),
    swingOnEnterAnimation(),
    tadaOnEnterAnimation(),
    wobbleOnEnterAnimation(),
    jelloOnEnterAnimation(),
];
