export enum SCREEN_SIZE {
  XS,
  SM,
  MD,
  LG,
  XL
}


export enum FieldType {
  TEXT, NUMBER, DATE, DATE_TIME, DROPDOWN,
  CHECK_BOX, TEMPLATE, TEXT_BOX, NUMBER_BOX, DATE_BOX, DATE_TIME_BOX, RADIO_BOX, TEXT_AREA_BOX,
  HEAD, CHECK_BOX_GROUP, SQUARE, CIRCLE,
  TEXT_DISPLAY, NUMBER_DISPLAY, DATE_DISPLAY, DATE_TIME_DISPLAY, DROPDOWN_DISPLAY
}
